# Generated by Django 6.0 on 2026-04-01 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fish', '0001_initial'),
        ('ponds', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stocking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fish_count', models.PositiveIntegerField()),
                ('initial_avg_weight_grams', models.PositiveIntegerField()),
                ('price_per_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stocking_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('fish_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fish.fishtype')),
                ('pond', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stockings', to='ponds.pond')),
            ],
        ),
    ]
