# Generated by Django 6.0 on 2026-04-01 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stocking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sampling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_date', models.DateField()),
                ('number_of_samples', models.PositiveIntegerField()),
                ('batch_size', models.PositiveIntegerField()),
                ('total_weight_grams', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('stocking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='samplings', to='stocking.stocking')),
            ],
        ),
    ]
