# Generated by Django 6.0 on 2026-04-01 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0001_initial'),
        ('ponds', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedpurchase',
            name='pond',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ponds.pond'),
            preserve_default=False,
        ),
    ]
