# Generated by Django 6.0 on 2026-04-01 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stocking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MortalityReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mortality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('dead_count', models.PositiveIntegerField()),
                ('stocking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mortalities', to='stocking.stocking')),
                ('reason', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mortality.mortalityreason')),
            ],
        ),
    ]
